services:
  - type: web
    name: marketbuddy-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: BOT_TOKEN
        value: 8241472299:AAGhewPu-VZFXpuLyVBlhRZYrGPgxpCb7mI
      - key: ADMIN_CHAT_ID
        value: "2110121880"
